name: CI

on:
  pull_request:
    branches:
      - master

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  node-version: "22.21"

jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ env.node-version }}
          cache: yarn
          cache-dependency-path: "**/yarn.lock"

      - name: Install deps
        run: yarn install --prefer-offline --frozen-lockfile

      - name: Codegen & check
        run: ./bin/codegen-check.sh

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint

      - name: Format check
        run: yarn prettier . --list-different
